
#THE MODELS USED
INSTANCE_CONFIG = "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
CHECKPOINT_URL = "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
KEYPOINT_CONFIG = "COCO-Keypoints/keypoint_rcnn_X_101_32x8d_FPN_3x.yaml"

MODEL = "ResNext-101_fold_01.pth"


#THE PATH TO OUR DATA
PHOTO_PATH = "C:\\Users\\ldunc\\OneDrive\\_WORKSPACE\\NEW_DET_NEW\\tests\\Test 19\\Photos"
VIDEO_PATH = "C:\\Users\\ldunc\\OneDrive\\_WORKSPACE\\NEW_DET_NEW\\tests\\Test 19\\JMZAE1363.MOV"
OUT_VIDEO_PATH = "C:\\Users\\ldunc\\OneDrive\\_WORKSPACE\\NEW_DET_NEW\\OUTPUT.MP4"


#THE ERROR TOLERATED FOR VALID PREDICTIONS
ERROR_TOLERANCE = 0.2

#NUMBER OF FRAMES USED 1/N
N_FRAME = 3

#THE AOV OF THE CAMERA USED
HAOV = 108
VAOV = 85


#RATIOS BETWEEN IMAGES AND PHOTOS
PHOTO_X = -1
PHOTO_Y = -1

DEGREE_PER_PIXEL_X = -1
DEGREE_PER_PIXEL_Y = -1


#DATABASE IDS TO START USING

DB_FRAGMENT_ID = 10000000
DB_FRAME_ID =    10000000
